[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = 'call kohei#hook#deoplete#hook_source()'
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_source = 'call kohei#hook#denite#hook_source()'
on_map = ['<Space>f', '<Space>F', '<Space>N', '<Space>G', '<Space>b', '<Space><Space>']

[[plugins]]
repo = 'tpope/vim-dispatch'
on_ft = [ 'cs', 'csi', 'csx' ]

[[plugins]]
repo = 'vim-syntastic/syntastic'
hook_source = 'call kohei#hook#syntastic#hook_source()'
on_ft = [ 'cs' ]
